# Generated by Django 6.0.6 on 2026-06-13 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="condition_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tasks/conditions/",
                verbose_name="Изображение к условию",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="explanation_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tasks/explanations/",
                verbose_name="Изображение к пояснению",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="answer",
            field=models.CharField(max_length=100, verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="task",
            name="condition",
            field=models.TextField(verbose_name="Условие"),
        ),
        migrations.AlterField(
            model_name="task",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "База"), ("hard", "Профиль")],
                default="easy",
                max_length=20,
                verbose_name="Сложность",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="explanation",
            field=models.TextField(blank=True, verbose_name="Пояснение"),
        ),
        migrations.AlterField(
            model_name="task",
            name="number",
            field=models.PositiveIntegerField(verbose_name="Номер задания"),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="task",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="tasks.topic",
                verbose_name="Тема",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название темы"),
        ),
    ]
